# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Diataxis template documentation
copyright: Copyright &copy; 2020 - 2024 Robbie Kouwenberg

repo_url: https://github.com/robbiekouwenberg/diataxis-template.git

# by default mkdocs.yml and docs/ are included in the watched directories, add others accordingly here
watch:
  - README.md
  - LICENSE.md

plugins:
  - search
  - awesome-pages
  - pagetree
  - print-site:
      print_page_title: Diataxis template documentation
      add_table_of_contents: false
      enumerate_headings: false
      enumerate_figures: false
      add_cover_page: false
      exclude:
        - index.md
        - concepts/index.md
        #- concepts/working-with-documentation.md
        - how-to/index.md
        #- how-to/start-local-documentation-server.md
        - how-to/troubleshooting/index.md
        - reference/index.md
        #- reference/diataxis-documentation.md
        - reference/decisions/index.md
        - reference/faq/index.md
        - reference/license.md
        - tutorials/index.md
        #- tutorials/getting-started.md
        #- tutorials/starting-doc-server.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: black
    secondary: yellow
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections 
    - navigation.expand 
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - def_list
  - pymdownx.tasklist:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true